### ISSUE TITLE
Finding large text not confined to lines

### ISSUE THREAD

**Issue by AdelleBernal** [tfeldmann/simplematch#23]
Hi, I'm not a tech person, so I need to search in text files very often, not in programming language scripts. I wonder if your tool can be only used to find expressions in lines (eg., programming-oriented) or for example, could it also identify sentences that start with  e.g., "chemistry is an" and end with "for the fast and efficient covalent," even if they are on different lines? Perhaps using a format like "chemistry is an * for the fast and efficient covalent"?, where * can imply any text and as multiple words.

**Comment by tfeldmann** [comment]
Hi I guess this is not in the scope of this library. But have a look at regular expressions:

https://regex101.com/r/oiynqp/1
